#!/usr/bin/env python3
"""render_zccm_dag.py — wrap the formulation DAG's mermaid block in a
self-contained HTML page (mermaid.js via CDN) for browser viewing.

Generates: results/figures/zccm_formulation_dag.html
Source:    reformulate/z4c-CMM/synthesis_z4c-CCM/formulation_dag.md
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "reformulate/z4c-CMM/synthesis_z4c-CCM/formulation_dag.md"
OUT = ROOT / "results/figures/zccm_formulation_dag.html"

block = re.search(r"```mermaid\n(.*?)```", DOC.read_text(encoding="utf-8"), re.S).group(1)
OUT.write_text(f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Z4c-CCM Formulation DAG</title>
<script type="module">
import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
mermaid.initialize({{ startOnLoad: true, maxTextSize: 200000, flowchart: {{ useMaxWidth: false }} }});
</script>
<style>body{{font-family:sans-serif;margin:1rem}}#legend span{{padding:2px 8px;margin-right:8px;border-radius:4px}}</style>
</head><body>
<h2>Z4c-CCM Formulation DAG — synthesis of arXiv:1010.0523v2 + 2007.01339 + 2308.10361</h2>
<p id="legend"><span style="background:#dbeafe">P1 Z4c CPBC</span>
<span style="background:#dcfce7">P2 CCE</span>
<span style="background:#fef3c7">P3 GH-CCM</span>
<span style="background:#fde2e2">NEW Z4c-CCM</span>
&nbsp;Generated by scripts/render_zccm_dag.py from formulation_dag.md
(verifier: results/numerical/zccm_dag_check.txt)</p>
<pre class="mermaid">
{block}
</pre>
</body></html>
""", encoding="utf-8")
print(f"rendered: {OUT}")
